// import { RiFilePaperLine } from "react-icons/ri";
// import { SlCalender } from "react-icons/sl";
// import { BiStopwatch } from "react-icons/bi";

export default {
  navLinks: [
    {
      id: "1",
      title: "How it works ^",
    },
    {
      id: "2",
      title: "FAQ",
    },
    {
      id: "3",
      title: "Testimonial",
    },
    {
      id: "4",
      title: "Trading",
    },
    {
      id: "5",
      title: "contact",
    },
    {
      id: "6",
      title: "Careers",
    },
    {
      id: "7",
      title: "Client Area",
    },
  ],
  statlinks: [
    {
      id: 1,
      figure: "$130M+",
      text: "paid out to FTMO traders",
    },
    {
      id: 2,
      figure: "180+",
      text: "No. of countries with traders registered at FTMO",
    },
    {
      id: 3,
      figure: "16M+",
      text: "No. of trades opened every month",
    },
    {
      id: 4,
      figure: "8h",
      text: "Avg payout processing time",
    },
  ],
  imgLinks: [
    {
      id: 1,
      link: "https://ftmo.com/wp-content/themes/ftmo-com/public/images/svg/awards/ey.svg",
    },
    {
      id: 2,
      link: "https://ftmo.com/wp-content/themes/ftmo-com/public/images/svg/awards/forbes.svg",
    },
    {
      id: 3,
      link: "https://ftmo.com/wp-content/themes/ftmo-com/public/images/svg/awards/deloitte_2022.svg",
    },
    {
      id: 4,
      link: "https://ftmo.com/wp-content/themes/ftmo-com/public/images/svg/awards/deloitte_2021.svg",
    },
    {
      id: 5,
      link: "https://ftmo.com/wp-content/themes/ftmo-com/public/images/svg/awards/deloitte_2020.svg",
    },
    {
      id: 6,
      link: "https://ftmo.com/wp-content/themes/ftmo-com/public/images/svg/awards/deloitte_2019.svg",
    },
  ],
  Eval: [
    {
      id: 1,
      No: "01.",
      title: "FTMO Challenge",
      text: "An FTMO Challenge is the first step of the Evaluation Process. You need to succeed here to advance into the Verification stage. Prove your trading skills and discipline in observing the Trading Objectives.",
    },
    {
      id: 2,
      No: "02.",
      title: "Verification",
      text: "Verification is the second and the last step towards becoming an FTMO Trader. Once you pass the Verification stage and your results are verified, you will be offered to trade for our Proprietary Trading Firm.",
    },
  ],
  currency: [
    {
      id: 1,
      img: "https://ftmo.com/wp-content/plugins/trading-objectives/build/images/usd-round-flag.417cef31.png",
      sign: "USD",
    },
    {
      id: 2,
      img: "https://ftmo.com/wp-content/plugins/trading-objectives/build/images/gbp-round-flag.292cd401.png",
      sign: "GBP",
    },
    {
      id: 1,
      img: "https://ftmo.com/wp-content/plugins/trading-objectives/build/images/eur-round-flag.3ee46dd1.png",
      sign: "EUR",
    },
    {
      id: 1,
      img: "https://ftmo.com/wp-content/plugins/trading-objectives/build/images/czk-round-flag.4569f892.png",
      sign: "CZK",
    },
    {
      id: 1,
      img: "https://ftmo.com/wp-content/plugins/trading-objectives/build/images/cad-round-flag.8e4db08c.png",
      sign: "CAD",
    },
    {
      id: 1,
      img: "https://ftmo.com/wp-content/plugins/trading-objectives/build/images/aud-round-flag.1507fce3.png",
      sign: "AUD",
    },
    {
      id: 1,
      img: "https://ftmo.com/wp-content/plugins/trading-objectives/build/images/chf-round-flag.adfe7382.png",
      sign: "CHF",
    },
  ],
  amount: [
    {
      id: 1,
      size: "$10,000",
    },
    {
      id: 2,
      size: "$25,000",
    },
    {
      id: 3,
      size: "$50,000",
    },
    {
      id: 4,
      size: "$100,000",
    },
    {
      id: 5,
      size: "$200,000",
    },
  ],
  Table: [
    {
      id: 1,
      title: "trading period",
      step1: "30days",
      add: "+14days",
      step2: "60 Days",
      add2: "30",
      step3: "indefinite",
    },
    {
      id: 2,
      title: "Minimum trading days ",
      step1: "10 days",
      add: null,
      step2: "10 days",
      add2: null,
      step3: "X",
    },
    {
      id: 3,
      title: "Maximum Daily Loss",
      step1: "$500",
      add: null,
      step2: "$500",
      add2: null,
      step3: "$500",
    },
    {
      id: 4,
      title: "Maximum Loss",
      step1: "$1,000",
      add: null,
      step2: "$1,000",
      add2: null,
      step3: "$1,000",
    },
    {
      id: 5,
      title: "Profit Target",
      step1: "$1,000",
      add: null,
      step2: "$500",
      add2: null,
      step3: "X",
    },
    {
      id: 6,
      title: "Free Repeat",
      step1: "Yes",
      add: null,
      step2: "Yes",
      add2: null,
      step3: "X",
    },
    {
      id: 7,
      title: "Refundable Fee",
      step1: "€155",
      add: null,
      step2: "free",
      add2: null,
      step3: "refund",
    },
  ],
  feeda: [
    {
      id: 1,
      title: "Symbols",
      step1: "30days",
      add: "+14days",
      step2: "60 Days",
      add2: "30",
      step3: "indefinite",
    },
    {
      id: 2,
      title: "Bid Price ",
      step1: "10 days",
      add: null,
      step2: "10 days",
      add2: null,
      step3: "X",
    },
    {
      id: 3,
      title: "Ask Price",
      step1: "$500",
      add: null,
      step2: "$500",
      add2: null,
      step3: "$500",
    },
    {
      id: 4,
      title: "Spread",
      step1: "$1,000",
      add: null,
      step2: "$1,000",
      add2: null,
      step3: "$1,000",
    },
    {
      id: 5,
      title: "Comissions",
      step1: "$1,000",
      add: null,
      step2: "$500",
      add2: null,
      step3: "X",
    },
    {
      id: 6,
      title: "Overall Costs",
      step1: "Yes",
      add: null,
      step2: "Yes",
      add2: null,
      step3: "X",
    },
    {
      id: 7,
      title: "Refundable Fee",
      step1: "€155",
      add: null,
      step2: "free",
      add2: null,
      step3: "refund",
    },
  ],
  foreHead: [
    {
      id: "head 1",
      head: "Symbol",
    },
    {
      id: "head 2",
      head: "Bid Price",
    },
    {
      id: "head 3",
      head: "Ask Price",
    },
    {
      id: "head 4",
      head: "Spread",
    },
    {
      id: "head 5",
      head: "Commissions",
    },
    {
      id: "head 6",
      head: "Overall Costs",
    },
  ],
  Forex: [
    {
      id: 1,
      Pair: "EURUSD",
      p1: 1.06829,
      p2: 1.06892,
      p3: 0.06804,
      comm: " 3.00",
      cost: 0.30002,
    },
    {
      id: 1,
      Pair: "GBPUSD",
      p1: 1.2433,
      p2: 1.24334,
      p3: 0.243,
      comm: " 3.00",
      cost: 0.30012,
    },
    {
      id: 1,
      Pair: "EURGBP",
      p1: 0.85889,
      p2: 0.85829,
      p3: 0.85823,
      comm: "3.00",
      cost: 0.24002,
    },
    {
      id: 1,
      Pair: "USDCAD",
      p1: 1.35708,
      p2: 1.35711,
      p3: 1.35728,
      comm: "3.00",
      cost: 0.40002,
    },
    {
      id: 1,
      Pair: "USDJPY",
      p1: 139.639,
      p2: 139.651,
      p3: 139.6,
      comm: "3.00",
      cost: 0.40003,
    },
  ],
  indexes: [
    {
      id: 1,
      Pair: "US30.cash",
      p1: "32,953.20",
      p2: "32,951.70",
      p3: "1.50",
      comm: " 0.00",
      cost: "1.50",
    },
    {
      id: 1,
      Pair: "US100.cash",
      p1: "14,257.33",
      p2: "14,247.00",
      p3: " 2.00",
      comm: "0.00",
      cost: " 1.90",
    },
    {
      id: 1,
      Pair: "US500.cash",
      p1: "4,188.90",
      p2: "4,189.00",
      p3: "0.60",
      comm: "0.00",
      cost: "0.60",
    },
    {
      id: 1,
      Pair: "US2000.cash",
      p1: "1,754.60",
      p2: "1,754.90",
      p3: "0.20",
      comm: "0.00",
      cost: "0.20",
    },
    {
      id: 1,
      Pair: "GER40.cash",
      p1: "15,837.50",
      p2: "15,838.80",
      p3: "0.80",
      comm: "0.00",
      cost: "0.80",
    },
  ],
  cryptoData: [
    {
      id: 1,
      Pair: "BTCUSD",
      p1: "35,872.50",
      p2: "35,874.20",
      p3: "1.70",
      comm: "0.00",
      cost: "1.70",
    },
    {
      id: 2,
      Pair: "ETHUSD",
      p1: "2,281.80",
      p2: "2,280.50",
      p3: "1.30",
      comm: "0.00",
      cost: "1.30",
    },
    {
      id: 3,
      Pair: "LTCUSD",
      p1: "150.90",
      p2: "150.95",
      p3: "0.05",
      comm: "0.00",
      cost: "0.05",
    },
    {
      id: 4,
      Pair: "XRPUSD",
      p1: "0.6408",
      p2: "0.6407",
      p3: "0.0001",
      comm: "0.00",
      cost: "0.0001",
    },
    {
      id: 5,
      Pair: "DASHUSD",
      p1: "150.20",
      p2: "150.25",
      p3: "0.05",
      comm: "0.00",
      cost: "0.05",
    },
  ],
  commoditiesData: [
    {
      id: 1,
      Pair: "XAUUSD",
      p1: "1,285.50",
      p2: "1,285.60",
      p3: "0.10",
      comm: "0.00",
      cost: "0.10",
    },
    {
      id: 2,
      Pair: "XAGUSD",
      p1: "17.40",
      p2: "17.41",
      p3: "0.01",
      comm: "0.00",
      cost: "0.01",
    },
    {
      id: 3,
      Pair: "XPDUSD",
      p1: "2,371.20",
      p2: "2,371.30",
      p3: "0.10",
      comm: "0.00",
      cost: "0.10",
    },
    {
      id: 4,
      Pair: "XPTUSD",
      p1: "1,087.80",
      p2: "1,087.90",
      p3: "0.10",
      comm: "0.00",
      cost: "0.10",
    },
    {
      id: 5,
      Pair: "USOIL.cash",
      p1: "62.15",
      p2: "62.20",
      p3: "0.05",
      comm: "0.00",
      cost: "0.05",
    },
  ],
  CustomData: [
    {
      id: 1,
      Pair: "---",
      p1: "---",
      p2: "---",
      p3: "---",
      comm: "---",
      cost: "---",
    },
    {
      id: 1,
      Pair: "---",
      p1: "---",
      p2: "---",
      p3: "---",
      comm: "---",
      cost: "---",
    },
    {
      id: 1,
      Pair: "---",
      p1: "---",
      p2: "---",
      p3: "---",
      comm: "---",
      cost: "---",
    },
    {
      id: 1,
      Pair: "---",
      p1: "---",
      p2: "---",
      p3: "---",
      comm: "---",
      cost: "---",
    },
    {
      id: 1,
      Pair: "---",
      p1: "---",
      p2: "---",
      p3: "---",
      comm: "---",
      cost: "---",
    },
  ],

  PropData1: [
    {
      id: 1,
      num: "01",
      title: "Benefit from our custom trading apps",
      img: "https://ftmo.com/wp-content/uploads/2022/11/01.jpg",
      text: "We’ve developed several apps for our traders. Some of them will help you with discipline, while others can assist with journaling or analysing the markets.",
      btnText: "Learn more",
    },
  ],
  PropData2: [
    {
      id: 2,
      num: "02",
      title: "Account Analysis",
      img: "https://ftmo.com/wp-content/uploads/2022/11/02.jpg",
      text: "When we decided to create this project, we knew that we have to offer our traders an unbiased look at their trading results. Why? Because it does not matter if the trader is a beginner or a professional, another opinion is always invaluable. For many traders, trading is also a lonely activity where many times, even your closest ones do not understand what you do on your computer for so many hours.",
      btnText: "Take a look",
    },
  ],
  PropData3: [
    {
      id: 3,
      num: "03",
      title: "Customer Support",
      img: "https://ftmo.com/wp-content/uploads/2023/01/03-customer-support.jpg",
      text: "Communication with traders is absolutely essential for us. We strive to assist not only in the process of becoming the FTMO Trader but also after that. Our qualified Customer Support specialists are always there for you via email, phone, or live chat. We communicate in 17 global languages and our Customer Support is rated as one of the best in the industry.",
      btnText: "Chat with us",
    },
  ],
  PropData4: [
    {
      id: 4,
      num: "04",
      title: "Trading Academy",
      img: "https://ftmo.com/wp-content/uploads/2022/11/04.jpg",
      text: "For beginner traders, we’ve prepared tutorials to help you get started with platforms and trading basics. In addition, we organize educational webinars on advanced trading topics and cooperate with well-known traders and mentors.",
      btnText: "Sign up",
    },
  ],
  PropData5: [
    {
      id: 5,
      num: "05",
      title: "Performance Coach",
      img: "https://ftmo.com/wp-content/uploads/2022/11/05.jpg",
      text: "In order to suppress bad habits and unwanted behaviour, it is essential to find a source of such behaviour and this isn’t always easy. For this reason, we have hired qualified Performance coaches for our team.  Our Performance coaches will lay down some particular questions specific to every individual and will try to guide you to understand the problems. Mutual cooperation should result in a long-term solution and eliminate unwanted manners and consequently lead to better trading results.",
      btnText: "Learn more",
    },
  ],
  Cards: [
    {
      id: "id 1",
      title: "The best trading conditions",
      text: "FTMO Solution with a wide choice of assets across the board, with very low commissions and super-raw spreads.",
      img: "",
    },
    {
      id: "id 2",
      title: "Leverage 1:100",
      text: "Use professional trader’s leverage to your advantage with no imposed limits on position sizing.",
      img: "",
    },
    {
      id: "id 3",
      title: "One-time fee only",
      text: "No recurrent charges, no membership or other hidden fees. Moreover, the fee is automatically reimbursed to you with the first Profit Split.",
      img: "",
    },
    {
      id: "id 4",
      title: "The most popular trading platforms",
      text: "MT4, MT5, or cTrader. Choose yourself!",
      img: "",
    },
    {
      id: "id 5",
      title: "No limits on trading style!",
      text: "Trade your own trading strategy with no limits or restrictions. You can use EAs, hedging or trade discretionary.",
      img: "",
    },
    {
      id: "id 6",
      title: "Trade every instrument you want",
      text: "Forex, Commodities, Indices, Crypto, Stocks, Bonds.",
      img: "",
    },
  ],
  reviews: [
    {
      title: "Great service!",
      description: "I had an amazing experience with FTMO. Highly recommended.",
      rating: 5,
      author: "John Doe",
    },
    {
      title: "Impressive platform",
      description:
        "FTMO provides a user-friendly platform with excellent features.",
      rating: 4,
      author: "Jane Smith",
    },
  ],
};
